# Generated by Django 6.0 on 2026-02-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=1, null=True),
        ),
    ]
