# Generated by Django 6.0 on 2026-02-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_image_urls_orderitem_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.URLField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
