# Generated by Django 6.0.2 on 2026-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_type_alter_order_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
