# Generated by Django 6.0 on 2026-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_cartitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
