# Generated by Django 6.0.2 on 2026-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_name_cartitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
        ),
    ]
